name: Generate livestreams
on:
  schedule:
    - cron: "45 */2 * * *"
  workflow_dispatch:
jobs:
  workflow_dispatch:
    runs-on: ubuntu-18.04
    steps:
     - name: Install youtube-dl
       run: |
        sudo curl -L https://yt-dl.org/downloads/latest/youtube-dl -o /usr/local/bin/youtube-dl
        sudo chmod a+rx /usr/local/bin/youtube-dl
     - name: RTL
       run: |
        mkdir "DE"
        cd DE
        touch ./RTL.m3u8
        sudo cat >./RTL.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=5400000
        $(youtube-dl -g https://www.2ix2.com/rtl-live/)
        EOL
     - name: RTL 2
       run: |
        cd DE
        touch ./RTL2.m3u8
        sudo cat >./RTL2.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=5400000
        $(youtube-dl -g https://www.2ix2.com/rtl2-live/)
        EOL
     - name: RTL Nitro
       run: |
        cd DE
        touch ./RTLNitro.m3u8
        sudo cat >./RTLNitro.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=5400000
        $(youtube-dl -g https://www.2ix2.com/rtl-nitro-hd/)
        EOL
     - name: Super RTL
       run: |
        cd DE
        touch ./SuperRTL.m3u8
        sudo cat >./SuperRTL.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=5400000
        $(youtube-dl -g https://www.2ix2.com/super-rtl-live/)
        EOL
     - name: ZDF
       run: |
        cd DE
        touch ./ZDF.m3u8
        sudo cat >./ZDF.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=5400000
        $(youtube-dl -g https://www.2ix2.com/zdf/)
        EOL
     - name: ZDFinfo
       run: |
        cd DE
        touch ./ZDFinfo.m3u8
        sudo cat >./ZDFinfo.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=5400000
        $(youtube-dl -g https://www.2ix2.com/zdfinfo/)
        EOL
     - name: ZDFneo
       run: |
        cd DE
        touch ./ZDFneo.m3u8
        sudo cat >./ZDFneo.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=5400000
        $(youtube-dl -g https://www.2ix2.com/zdfneo/)
        EOL
     - name: ProSieben
       run: |
        cd DE
        touch ./pro7.m3u8
        sudo cat >./pro7.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=5400000
        $(youtube-dl -g https://www.2ix2.com/pro7/)
        EOL
     - name: ProSieben MAXX
       run: |
        cd DE
        touch ./pro7max.m3u8
        sudo cat >./pro7max.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=5400000
        $(youtube-dl -g https://www.2ix2.com/prosieben-maxx/)
        EOL
     - name: Kabel Eins
       run: |
        cd DE
        touch ./kabel1.m3u8
        sudo cat >./kabel1.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=5400000
        $(youtube-dl -g https://www.2ix2.com/kabel-1/)
        EOL
     - name: Kabel Eins Doku
       run: |
        cd DE
        touch ./kabel1doku.m3u8
        sudo cat >./kabel1doku.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=5400000
        $(youtube-dl -g https://www.2ix2.com/kabel-1-doku/)
        EOL
     - name: Sat1
       run: |
        cd DE
        touch ./sat1.m3u8
        sudo cat >./sat1.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=5400000
        $(youtube-dl -g https://www.2ix2.com/sat1/)
        EOL
     - name: Sat1 Gold
       run: |
        cd DE
        touch ./sat1gold.m3u8
        sudo cat >./sat1gold.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=5400000
        $(youtube-dl -g https://www.2ix2.com/sat1-gold/)
        EOL
     - name: SIXX
       run: |
        cd DE
        touch ./sixx.m3u8
        sudo cat >./sixx.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=5400000
        $(youtube-dl -g https://www.2ix2.com/sixx/)
        EOL
     - name: VOX
       run: |
        cd DE
        touch ./VOX.m3u8
        sudo cat >./VOX.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=5400000
        $(youtube-dl -g https://www.2ix2.com/vox/)
     - name: n-tv
       run: |
        cd DE
        touch ./n-tv.m3u8
        sudo cat >./n-tv.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=5400000
        $(youtube-dl -g https://www.2ix2.com/n-tv-live/)
        EOL
     - name: DMAX
       run: |
        cd DE
        touch ./DMAX.m3u8
        sudo cat >./DMAX.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=5400000
        $(youtube-dl -g https://www.2ix2.com/dmax/)
        EOL
     - name: TLC
       run: |
        cd DE
        touch ./TLC.m3u8
        sudo cat >./TLC.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=5400000
        $(youtube-dl -g https://www.2ix2.com/tlc/)
        EOL
     - name: Sky Sport News
       run: |
        cd DE
        touch ./SkySN.m3u8
        sudo cat >./SkySN.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=5400000
        $(youtube-dl -g https://www.2ix2.com/sky-sport-news-hd-snhd/)
        EOL
     - name: KIKA
       run: |
        cd DE
        touch ./KIKA.m3u8
        sudo cat >./KIKA.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=5400000
        $(youtube-dl -g https://www.2ix2.com/kika/)
        EOL
     - name: Disney Channel
       run: |
        cd DE
        touch ./DisneyChannel.m3u8
        sudo cat >./DisneyChannel.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=5400000
        $(youtube-dl -g https://www.2ix2.com/disney-channel/)
        EOL
     - name: Tele5
       run: |
        cd DE
        touch ./Tele5.m3u8
        sudo cat >./Tele5.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=5400000
        $(youtube-dl -g https://www.2ix2.com/tele-5/)
        EOL
     - name: Comedy Central
       run: |
        cd DE
        touch ./ComedyCentral.m3u8
        sudo cat >./ComedyCentral.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=5400000
        $(youtube-dl -g https://www.2ix2.com/comedy-central/)
        EOL
     - name: 3sat
       run: |
        cd DE
        touch ./3sat.m3u8
        sudo cat >./3sat.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=5400000
        $(youtube-dl -g https://www.2ix2.com/3sat/)
        EOL
     - name: Tele5
       run: |
        cd DE
        touch ./Tele5.m3u8
        sudo cat >./Tele5.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=5400000
        $(youtube-dl -g https://www.2ix2.com/tele-5/)
        EOL
     - name: WELT
       run: |
        cd DE
        touch ./WELT.m3u8
        sudo cat >./WELT.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=5400000
        $(youtube-dl -g https://www.2ix2.com/welt/)
        EOL
     - name: arte
       run: |
        cd DE
        touch ./arte.m3u8
        sudo cat >./arte.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=5400000
        $(youtube-dl -g https://www.2ix2.com/arte/)
        EOL
     - name: Nickelodeon
       run: |
        cd DE
        touch ./nick.m3u8
        sudo cat >./nick.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=5400000
        $(youtube-dl -g https://www.2ix2.com/nickelodeon/)
        EOL
     - name: MTV
       run: |
        cd DE
        touch ./MTV.m3u8
        sudo cat >./MTV.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=5400000
        $(youtube-dl -g https://www.2ix2.com/mtv/)
        EOL
     - name: Das Erste
       run: |
        cd DE
        touch ./DasErste.m3u8
        sudo cat >./DasErste.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=5400000
        $(youtube-dl -g https://www.2ix2.com/ard/)
        EOL
     - name: ARD One
       run: |
        cd DE
        touch ./one.m3u8
        sudo cat >./one.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=5400000
        $(youtube-dl -g https://www.2ix2.com/one-tv/)
        EOL
     - name: Phoenix
       run: |
        cd DE
        touch ./Phoenix.m3u8
        sudo cat >./Phoenix.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=5400000
        $(youtube-dl -g https://www.2ix2.com/phoenix/)
        EOL
     - name: ORF 1
       run: |
        mkdir AT
        cd AT
        touch ./ORF1.m3u8
        sudo cat >./ORF1.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=5400000
        $(youtube-dl -g https://www.2ix2.com/orf1/)
        EOL
     - name: ORF 2
       run: |
        cd AT
        touch ./ORF2.m3u8
        sudo cat >./ORF2.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=5400000
        $(youtube-dl -g https://www.2ix2.com/orf2/)
        EOL
     - name: ORF 3
       run: |
        cd AT
        touch ./ORF3.m3u8
        sudo cat >./ORF3.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=5400000
        $(youtube-dl -g https://www.2ix2.com/orf3/)
        EOL
     - name: Servus TV
       run: |
        cd AT
        touch ./servus.m3u8
        sudo cat >./servus.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=5400000
        $(youtube-dl -g https://www.2ix2.com/servus-tv/)
        EOL
     - name: Landle
       run: |
        cd AT
        touch ./landle.m3u8
        sudo cat >./landle.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=5400000
        $(youtube-dl -g https://www.2ix2.com/laendle-tv/)
        EOL
     - name: SRF 1
       run: |
        mkdir "CH"
        cd CH
        touch ./SRF2.m3u8
        sudo cat >./SRF2.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=5400000
        $(youtube-dl -g https://www.2ix2.com/srf-2/)
        EOL
     - name: SRF 2
       run: |
        cd CH
        touch ./SRF2.m3u8
        sudo cat >./SRF2.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=5400000
        $(youtube-dl -g https://www.2ix2.com/srf-2/)
        EOL
     - name: SRF Info
       run: |
        cd CH
        touch ./ORF3.m3u8
        sudo cat >./ORF3.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=5400000
        $(youtube-dl -g https://www.2ix2.com/srf-info/)
        EOL
     - name: 4+
       run: |
        cd CH
        touch ./4plus.m3u8
        sudo cat >./4plus.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=5400000
        $(youtube-dl -g https://www.2ix2.com/4-plus/)
        EOL
     - name: RTVE 24h
       run: |
        mkdir "ES"
        cd ES
        touch ./24h.m3u8
        sudo cat >./24h.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=5400000
        $(youtube-dl -g https://youtube.com/rtvenoticias/live)
        EOL
     - name: 7NN
       run: |
        cd ES
        touch ./7nn.m3u8
        sudo cat >./7nn.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=5400000
        $(youtube-dl -g https://twitch.tv/7nntv)
        EOL
     - name: Libertad Digital
       run: |
        cd ES
        touch ./libertaddigital.m3u8
        sudo cat >./libertaddigital.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=5400000
        $(youtube-dl -g https://dai.ly/xnm032)
        EOL
     - name: Dejate de Historias - Madrid
       run: |
        cd ES
        mkdir "Madrid"
        cd Madrid
        touch ./DH.m3u8
        sudo cat >./DH.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=5400000
        $(youtube-dl -g https://youtube.com/channel/UChMCkc02GVSi89TrvhbRasA/live)
        EOL
     - name: A24
       run: |
        mkdir "AR"
        cd AR
        touch ./A24.m3u8
        sudo cat >./A24.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=5400000
        $(youtube-dl -g https://youtube.com/A24com/live)
        EOL
     - name: America
       run: |
        cd AR
        touch ./America.m3u8
        sudo cat >./America.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=5400000
        $(youtube-dl -g https://youtube.com/americaenvivo/live)
        EOL
     - name: TVP Argentina
       run: |
        cd AR
        touch ./TVP.m3u8
        sudo cat >./TVP.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=5400000
        $(youtube-dl -g https://youtube.com/TVPublicaArgentina/live)
        EOL
     - name: LN+
       run: |
        cd AR
        touch ./LNMas.m3u8
        sudo cat >./LNMas.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=5400000
        $(youtube-dl -g https://youtube.com/LaNacionMas/live)
        EOL
     - name: C5N
       run: |
        cd AR
        touch ./C5N.m3u8
        sudo cat >./C5N.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=5400000
        $(youtube-dl -g https://youtube.com/c5n/live)
        EOL
     - name: CNN
       run: |
        mkdir "US"
        cd US
        touch ./CNN.m3u8
        sudo cat >./CNN.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=5400000
        $(youtube-dl -g https://www.livenewsnow.com/american/cnn-live.html)
        EOL
     - name: MSNBC
       run: |
        cd US
        touch ./MSNBC.m3u8
        sudo cat >./MSNBC.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=5400000
        $(youtube-dl -g https://livenewsmag.com/msnbc-live-tv)
        EOL
     - name: FBN
       run: |
        cd US
        touch ./FBN.m3u8
        sudo cat >./FBN.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=5400000
        $(youtube-dl -g https://www.livenewsnow.com/business/fox-business-network-fbn.html)
        EOL
     - name: NTV24
       run: |
        mkdir "JP"
        cd JP
        touch ./NTVNews24.m3u8
        sudo cat >./NTVNews24.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=5400000
        $(youtube-dl -g https://youtube.com/channel/UCuTAXTexrhetbOe3zgskJBQ/live)
        EOL
     - name: TBS News
       run: |
        cd JP
        touch ./TBSNews.m3u8
        sudo cat >./TBSNews.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=5400000
        $(youtube-dl -g https://youtube.com/tbsnews/live)
        EOL
     - name: NHK World 
       run: |
        cd JP
        touch ./NHKWorld.m3u8
        sudo cat >./NHKWorld.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=5400000
        $(youtube-dl -g https://youtube.com/NHKWORLDJAPAN/live)
        EOL
     - name : Upload artifact
       uses: actions/upload-artifact@master  https://youtube.com/channel/UCuTAXTexrhetbOe3zgskJBQ/live
       with:
        name: Push pt.1
        path: .
     - name: Push pt.2
       run: |
        git init
        git config --local user.name "actions"
        git config --local user.email "action@github.com" 
        git checkout -b live
        git add .
        git commit -m "Updates lives specified in extractor.yml"
        git remote add origin "https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}"
        git push -f -u origin live
