name: Generate livestreams
on:
  schedule:
    - cron: "45 */2 * * *"
  workflow_dispatch:
jobs:
  workflow_dispatch:
    runs-on: ubuntu-18.04
    steps:
     - name: Install youtube-dl
       run: |
        sudo curl -L https://yt-dl.org/downloads/latest/youtube-dl -o /usr/local/bin/youtube-dl
        sudo chmod a+rx /usr/local/bin/youtube-dl
     - name: RTVE 24h
       run: |
        mkdir "ES"
        cd ES
        touch ./24h.m3u8
        sudo cat >./24h.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=5400000
        $(youtube-dl -g https://youtube.com/rtvenoticias/live)
        EOL
     - name: 7NN
       run: |
        cd ES
        touch ./7nn.m3u8
        sudo cat >./7nn.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=5400000
        $(youtube-dl -g https://twitch.tv/7nntv)
        EOL
     - name: Libertad Digital
       run: |
        cd ES
        touch ./libertaddigital.m3u8
        sudo cat >./libertaddigital.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=5400000
        $(youtube-dl -g https://dai.ly/xnm032)
        EOL
     - name: Dejate de Historias - Madrid
       run: |
        cd ES
        mkdir "Madrid"
        cd Madrid
        touch ./DH.m3u8
        sudo cat >./DH.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=5400000
        $(youtube-dl -g https://youtube.com/channel/UChMCkc02GVSi89TrvhbRasA/live)
        EOL
     - name: A24
       run: |
        mkdir "AR"
        cd AR
        touch ./A24.m3u8
        sudo cat >./A24.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=5400000
        $(youtube-dl -g https://youtube.com/A24com/live)
        EOL
     - name: America
       run: |
        cd AR
        touch ./America.m3u8
        sudo cat >./America.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=5400000
        $(youtube-dl -g https://youtube.com/americaenvivo/live)
        EOL
     - name: TVP Argentina
       run: |
        cd AR
        touch ./TVP.m3u8
        sudo cat >./TVP.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=5400000
        $(youtube-dl -g https://youtube.com/TVPublicaArgentina/live)
        EOL
     - name: LN+
       run: |
        cd AR
        touch ./LNMas.m3u8
        sudo cat >./LNMas.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=5400000
        $(youtube-dl -g https://youtube.com/LaNacionMas/live)
        EOL
     - name: C5N
       run: |
        cd AR
        touch ./C5N.m3u8
        sudo cat >./C5N.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=5400000
        $(youtube-dl -g https://youtube.com/c5n/live)
        EOL
     - name: CNN
       run: |
        mkdir "US"
        cd US
        touch ./CNN.m3u8
        sudo cat >./CNN.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=5400000
        $(youtube-dl -g https://www.livenewsnow.com/american/cnn-live.html)
        EOL
     - name: MSNBC
       run: |
        cd US
        touch ./MSNBC.m3u8
        sudo cat >./MSNBC.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=5400000
        $(youtube-dl -g https://livenewsmag.com/msnbc-live-tv)
        EOL
     - name: FBN
       run: |
        cd US
        touch ./FBN.m3u8
        sudo cat >./FBN.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=5400000
        $(youtube-dl -g https://www.livenewsnow.com/business/fox-business-network-fbn.html)
        EOL
     - name: NTV24
       run: |
        mkdir "JP"
        cd JP
        touch ./NTVNews24.m3u8
        sudo cat >./NTVNews24.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=5400000
        $(youtube-dl -g https://youtube.com/channel/UCuTAXTexrhetbOe3zgskJBQ/live)
        EOL
     - name: TBS News
       run: |
        cd JP
        touch ./TBSNews.m3u8
        sudo cat >./TBSNews.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=5400000
        $(youtube-dl -g https://youtube.com/tbsnews/live)
        EOL
     - name: NHK World 
       run: |
        cd JP
        touch ./NHKWorld.m3u8
        sudo cat >./NHKWorld.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=5400000
        $(youtube-dl -g https://youtube.com/NHKWORLDJAPAN/live)
        EOL
     - name : Upload artifact
       uses: actions/upload-artifact@master
       with:
        name: Push pt.1
        path: .
     - name: Push pt.2
       run: |
        git init
        git config --local user.name "actions"
        git config --local user.email "action@github.com" 
        git checkout -b live
        git add .
        git commit -m "Updates lives specified in extractor.yml"
        git remote add origin "https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}"
        git push -f -u origin live
